import AuthSession from "../models/AuthSession.js";
vi.mock("../models/AuthSession.js", () => ({ default: { create: vi.fn(), deleteOne: vi.fn() } }));
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { randomBytes } from "node:crypto";
import jwt from "jsonwebtoken";
import router from "../routes/auth.js";
import { googleUpsert } from "../utils/googleUpsert.js";
const { verifyIdToken, authenticate } = vi.hoisted(() => ({ verifyIdToken: vi.fn(), authenticate: vi.fn(() => (req, res, next) => next()) }));
vi.mock("google-auth-library", () => ({ OAuth2Client: class { verifyIdToken(...args) { return verifyIdToken(...args); } } }));
vi.mock("passport", () => ({ default: { authenticate, serializeUser: vi.fn(), deserializeUser: vi.fn() } }));
vi.mock("../utils/googleUpsert.js", () => ({ googleUpsert: vi.fn() }));
vi.mock("../services/emailService.js", () => ({ sendVerificationEmail: vi.fn(), sendPasswordResetEmail: vi.fn(), sendEmailVerifyOtp: vi.fn() }));
const user = { _id: "000000000000000000000001", email: "google@example.test", role: "user", profileComplete: true };
const handler = path => router.stack.find(layer => layer.route?.path === path).route.stack.at(-1).handle;
const response = () => ({ status: vi.fn().mockReturnThis(), set: vi.fn(), json: vi.fn(), cookie: vi.fn(), redirect: vi.fn() });
beforeEach(() => { vi.stubEnv("JWT_SECRET", randomBytes(32).toString("hex")); });
afterEach(() => { vi.unstubAllEnvs(); vi.clearAllMocks(); });
it.each(["production", "development"])("preserves secure Google web cookie and signed session in %s", async env => {
  vi.stubEnv("NODE_ENV", env);
  const res = response();
  await handler("/google/callback")({ user, rememberMe: true }, res);
  const [name, token, options] = res.cookie.mock.calls[0];
  expect(name).toBe("token");
  expect(options).toMatchObject({ httpOnly: true, sameSite: "lax", secure: env === "production" });
  const payload = jwt.verify(token, process.env.JWT_SECRET);
  expect(payload.id).toBe(user._id);
  expect(payload.exp - payload.iat).toBe(30 * 24 * 60 * 60);
  expect(res.redirect.mock.calls[0][0]).toMatch(/\/auth\/callback$/);
});
it("preserves mobile Google verification and app session issuance", async () => {
  vi.stubEnv("GOOGLE_CLIENT_ID", "test-client-placeholder");
  verifyIdToken.mockResolvedValue({ getPayload: () => ({ email: user.email, sub: "google-id", picture: "" }) });
  googleUpsert.mockResolvedValue(user);
  const res = response();
  await handler("/google/mobile")({ body: { idToken: "google-token-placeholder" } }, res);
  expect(verifyIdToken).toHaveBeenCalledWith({ idToken: "google-token-placeholder", audience: "test-client-placeholder" });
  const payload = jwt.verify(res.json.mock.calls[0][0].token, process.env.JWT_SECRET);
  expect(payload.id).toBe(user._id);
  expect(payload.sid).toMatch(/^[a-f0-9]{64}$/);
  expect(payload.exp - payload.iat).toBe(12 * 3600);
  expect(AuthSession.create).toHaveBeenCalledWith(expect.objectContaining({ user: user._id, expiresAt: expect.any(Date) }));
  expect(res.cookie).not.toHaveBeenCalled();
});
it("rejects invalid mobile Google credentials", async () => {
  verifyIdToken.mockRejectedValue(new Error("invalid"));
  const res = response();
  await handler("/google/mobile")({ body: { idToken: "invalid" } }, res);
  expect(res.status).toHaveBeenCalledWith(401);
  expect(googleUpsert).not.toHaveBeenCalled();
});
