import { beforeAll, afterAll, afterEach, expect, it, vi } from "vitest";
import express from "express";
import { once } from "node:events";
import User from "../models/User.js";
const provider = vi.fn(async () => ({ response: { text: () => "{}" } }));
import { GoogleGenerativeAI } from "@google/generative-ai";
vi.mock("../middlewares/ensureAuth.js", () => ({ default: (req, res, next) => { req.user = { id: "507f1f77bcf86cd799439011" }; next(); } }));
import router from "../routes/ai.js";
import { PLOTWORLD_DRAW_ENABLED, PLOTWORLD_SCENE_AI_ENABLED } from "../../shared/features.js";
import { TOUR_STEPS } from "../../frontend/src/components/tour/TourSteps.jsx";
let server, base;
beforeAll(async () => { process.env.GEMINI_API_KEY="test"; vi.spyOn(GoogleGenerativeAI.prototype,"getGenerativeModel").mockReturnValue({generateContent:provider}); const app=express(); app.use(express.json()); app.use(router); server=app.listen(0,"127.0.0.1"); await once(server,"listening"); base=`http://127.0.0.1:${server.address().port}`; });
afterAll(async () => { await new Promise(resolve => server.close(resolve)); });
afterEach(() => { vi.clearAllMocks(); });
const post = path => fetch(base+"/plotworld/"+path,{ method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({character:{name:"Ada"},scenes:[{id:"1",title:"Start"}]}) });
it("launch flags and tour expose arc without drawing or scene AI",()=>{ expect(PLOTWORLD_DRAW_ENABLED).toBe(false); expect(PLOTWORLD_SCENE_AI_ENABLED).toBe(false); expect(TOUR_STEPS.plot.map(s=>s.target)).toEqual(expect.arrayContaining(["plotworld-board-tab","plotworld-ark-btn"])); expect(TOUR_STEPS.plot.some(s=>/ai-btn|cizim/.test(s.target))).toBe(false); });
it.each(["disabled","undecided"])("never calls a provider when global permission is %s",async preference=>{vi.spyOn(User,"findById").mockReturnValue({select:()=>({lean:async()=>({settings:{developmentCoach:preference}})})});expect((await post("arc-analysis")).status).toBe(403);expect(provider).not.toHaveBeenCalled();});
it("fails closed when preference cannot be read",async()=>{vi.spyOn(User,"findById").mockReturnValue({select:()=>({lean:async()=>{throw Error("offline")}})});expect((await post("arc-analysis")).status).toBe(503);expect(provider).not.toHaveBeenCalled();});
it("keeps arc analysis available with consent",async()=>{vi.spyOn(User,"findById").mockReturnValue({select:()=>({lean:async()=>({settings:{developmentCoach:"enabled"}})})});expect((await post("arc-analysis")).status).toBe(200);expect(provider).toHaveBeenCalledOnce();});
it("blocks all scene AI endpoints before provider calls",async()=>{for(const path of ["gap-analysis","scene-suggest","story-coach","scene-butterfly","scene-analyze","scene-strengthen","scene-coach"])expect((await post(path)).status).toBe(404);expect(provider).not.toHaveBeenCalled();});
