// Real-browser checks against actual components, with isolated in-memory API fixtures.
// PLAYWRIGHT_MODULE may point to an existing Playwright installation (file URL).
import { CHAPTER_HISTORY_ENABLED } from "../../shared/features.js";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import { validDevelopmentResult } from "../../backend/tests/fixtures/developmentResult.js";
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
const root = fileURLToPath(new URL("../", import.meta.url));
const artifacts = await mkdtemp(join(tmpdir(), "acb-writing-"));
const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>body{margin:0}*{box-sizing:border-box}</style></head><body><div id="root"></div><script type="module" src="/scripts/writing-fixture.jsx"></script></body></html>`;
const vite = await createServer({ root, server: { host: "127.0.0.1", port: 0 }, plugins: [{ name: "writing-fixture", configureServer(server) {
  server.middlewares.use(async (req, res, next) => {
    if (req.url?.split("?")[0] !== "/__writing-test") return next();
    res.setHeader("Content-Type", "text/html"); res.end(await server.transformIndexHtml(req.url, html));
  });
} }] });
let browser;
try {
  await vite.listen();
  console.log('Fixture server ready');
  browser = await chromium.launch({ channel: "chrome", headless: true });
  console.log('Browser ready');
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
  page.setDefaultTimeout(13000);
  const errors = []; page.on("pageerror", error => { errors.push(error.message); console.error(error.message); });
  page.on('console', message => { if (message.type() === 'error') console.error(message.text()); });
  let chapter = { _id: "chapter1", work: "work1", title: "Kıyıdaki Ev", status: "draft", order: 1, revision: 0, savedAt: new Date().toISOString(), content: Array.from({ length: 6 }, (_, i) => `<p>${(`Paragraf${i} deniz rüzgâr sessizlik kıyı. `).repeat(30)}</p>`).join("") };
  let developmentWords = 0, developmentRequests = 0, developmentCooldown = false, developmentComplete = false, analysisCount = 0, latestDevelopment = null;
  let coachPreference = "undecided", archive = [], preferenceReadFails = false;
  let dailySuccesses = 0;
  const quota = () => ({ dailyLimit: 2, used: developmentCooldown ? 2 : dailySuccesses, remaining: developmentCooldown ? 0 : Math.max(0, 2 - dailySuccesses), retryAfter: developmentCooldown || dailySuccesses >= 2 ? 3600 : 0 });
  let versions = [{ ...chapter, chapter: chapter._id }], note = null, puts = 0;
  await page.route("**/api/**", async route => {
    const request = route.request(), url = new URL(request.url());
    const path = url.pathname.split("/api")[1], method = request.method();
    const body = ["POST", "PUT", "PATCH"].includes(method) ? request.postDataJSON() : {};
    assert(!path.startsWith("/ai/"), "Writing controls must not call AI");
    let result = {}, status = 200;
    if (path === "/auth/me") result = { user: { _id: "writer1" } };
    else if (path === "/user/development-coach") {
      if (method === "PATCH") coachPreference = body.preference;
      result = { preference: coachPreference, message: "Tercihin kaydedildi. Ayarlar’dan değiştirebilirsin." };
      if (method === "GET" && preferenceReadFails) { status = 503; result = { message: "Fixture preference read failure" }; }
    }
    else if (path === "/chapters/development/work1/analyses") result = { items: archive, nextBefore: null };
    else if (path === "/chapters/development/work1") {
      if (method === "POST") {
        developmentRequests++;
        status = developmentCooldown ? 429 : 200;
        result = developmentCooldown ? { code: "DEVELOPMENT_DAILY_LIMIT", quota: quota(), message: "Yeni yazıların bir sonraki değerlendirme için birikmeye devam edecek." }
          : { status: "prepared", kind: "baseline", message: "Gelişim Koçu henüz kullanıma açılmadı." };
        if (developmentComplete) {
          status = 200; analysisCount++; dailySuccesses++; developmentWords = 0;
          latestDevelopment = { status: "complete", kind: "baseline", analyzedAt: new Date().toISOString(), result: validDevelopmentResult() };
          archive.unshift({ ...latestDevelopment, _id: "analysis-" + analysisCount, sequence: analysisCount });
          result = { ...latestDevelopment, development: { analysisCount, eligibleForDevelopmentReview: false, quota: quota() } };
        }
      } else result = { analysisCount, eligibleForDevelopmentReview: developmentWords >= 3000, quota: quota() };
    }
    else if (path === "/chapters/development/work1/latest") result = latestDevelopment;
    else if (path === "/chapters") result = { items: [{ _id: chapter._id, title: chapter.title, order: 1 }, { _id: "chapter2", title: "Ormandaki Yol", order: 2 }] };
    else if (path === "/chapters/chapter2" && method === "GET") result = { item: { ...chapter, _id: "chapter2", title: "Ormandaki Yol", order: 2, content: "<p>İkinci bölümün metni.</p>" } };
    else if (path === "/chapters/chapter1" && method === "GET") result = { item: chapter };
    else if (path === "/chapters/chapter1" && method === "PUT") {
      assert.equal(body.expectedRevision, chapter.revision);
      developmentWords += body.eligibleWordDelta || 0;
      puts++; chapter = { ...chapter, ...body, revision: chapter.revision + 1, savedAt: new Date().toISOString() };
      versions.push({ ...chapter, chapter: chapter._id }); result = { item: chapter, revision: chapter.revision, savedAt: chapter.savedAt, development: { eligibleForDevelopmentReview: developmentWords >= 3000 } };
    } else if (path === "/chapters/chapter1/checkpoint") {
      assert.equal(body.expectedRevision, chapter.revision);
      const item = versions.find(v => v.revision === body.expectedRevision);
      Object.assign(item, { isCheckpoint: true, label: body.label }); result = { item };
    } else if (path === "/chapters/chapter1/versions") result = { items: [...versions].reverse(), nextBefore: null };
    else if (/\/versions\/\d+\/restore$/.test(path)) {
      assert.equal(body.expectedRevision, chapter.revision);
      const selected = versions.find(v => v.revision === Number(path.split("/").at(-2)));
      chapter = { ...chapter, title: selected.title, content: selected.content, revision: chapter.revision + 1, savedAt: new Date().toISOString() };
      versions.push({ ...chapter }); result = { item: chapter, revision: chapter.revision, savedAt: chapter.savedAt };
    } else if (/\/versions\/\d+$/.test(path)) result = { item: versions.find(v => v.revision === Number(path.split("/").at(-1))) };
    else if (path === "/notes" && method === "POST") { note = { ...body, _id: "note1" }; result = { item: note }; }
    else if (path === "/notes/note1" && method === "PATCH") { note = { ...note, ...body }; result = { item: note }; }
    else if (path === "/user/tour-complete") result = {};
    else { status = 404; result = { message: "Unexpected fixture route " + path }; }
    await route.fulfill({ status, contentType: "application/json", body: JSON.stringify(result) });
  });
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/__writing-test`, { waitUntil: 'domcontentloaded' });
  await page.locator(".chapter-document").first().waitFor();
  await page.getByRole("button", { name: "Hayır, istemiyorum" }).waitFor();
  await page.screenshot({ path: join(artifacts, "development-consent.png") });
  await page.getByRole("button", { name: "Hayır, istemiyorum" }).click();
  await page.getByRole('dialog', { name: 'Yapay Zeka Gelişim Koçu tercihi' }).waitFor({ state: 'detached' });
  assert.equal(await page.locator('.development-archive').count(), 0);
  assert.equal(await page.locator('.cp-main .development-preference').count(), 0);
  assert.equal(coachPreference, "disabled");
  assert.equal(developmentRequests, 0);
  const initialTheme = await page.evaluate(() => document.documentElement.dataset.theme);
  await page.getByRole("button", { name: initialTheme === "light" ? "Karanlık moda geç" : "Aydınlık moda geç" }).click();
  const changedTheme = await page.evaluate(() => document.documentElement.dataset.theme); assert.notEqual(changedTheme, initialTheme);
  await page.reload(); await page.locator(".chapter-document").waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.dataset.theme), changedTheme);
  assert.equal(await page.locator(".cp-tools-menu .cp-theme-btn").count(), 0);
  assert.equal(await page.getByText("AI yorumla", { exact: true }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).count(), 0);
  const geometry = () => page.locator(".chapter-document").evaluateAll(nodes => nodes.slice(0, 2).map(node => { const r = node.getBoundingClientRect(), editor = node.querySelector('.rich-content'); return { x:r.x, y:r.y, width:r.width, height:r.height, overflow:getComputedStyle(editor).overflowY, scroll:editor.scrollHeight, client:editor.clientHeight }; }));
  let rects = await geometry(); assert.equal(rects.length, 1); assert(rects.every(r => r.overflow === "visible" && r.scroll <= r.client + 1));
  assert.equal(await page.getByTitle("Yan yana", { exact: true }).count(), 0);
  assert.equal(await page.locator(".cp-thumbs, .cp-split-column, .cp-view-toggle").count(), 0);
  await page.screenshot({ path: join(artifacts, "continuous.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(350); // allow the sidebar's responsive transition to finish
  rects = await geometry(); assert.equal(rects.length, 1);
  assert.equal(await page.getByRole("button", { name: "Geçmiş", exact: true }).count(), CHAPTER_HISTORY_ENABLED ? 1 : 0);
  assert(await page.getByRole("button", { name: "Odak", exact: true }).isVisible());
  assert(await page.locator(".cp-theme-btn").isVisible());
  for (const icon of await page.locator(".cp-compact-tool .cp-tb-btn-icon").all()) assert(await icon.isVisible());
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert(await page.locator('.cp-sidebar').evaluate(node => node.getBoundingClientRect().right <= 1));
  await page.screenshot({ path: join(artifacts, "mobile.png") });
  await page.setViewportSize({ width: 1600, height: 1000 });
  const editor = page.locator('.chapter-document .rich-content').first();
  await editor.fill('Uzun bölüm ' + 'deniz kıyı rüzgâr '.repeat(1000));
  await page.waitForFunction(() => document.querySelector('.cp-save-details summary')?.textContent === 'Kaydedildi');
  assert(puts > 0); assert(chapter.content.includes('Uzun bölüm'));
  rects = await geometry(); assert(rects[0].height > 1000); assert.equal(rects[0].overflow, 'visible');
  await editor.fill('Manuel kayıt denemesi.');
  await page.locator('.cp-save-details summary').click();
  await page.getByRole('button', { name: 'Şimdi kaydet', exact: true }).click();
  await page.locator('.cp-save-details summary').click();
  await page.waitForFunction(() => document.querySelector('.cp-save-details summary')?.textContent === 'Kaydedildi');
  assert(chapter.content.includes('Manuel kayıt'));
  await editor.fill('Bölüm değiştirirken korunan taslak.');
  await page.locator('.cp-ch-btn').nth(1).click();
  assert.equal(await page.locator('.chapter-document .rich-content').count(), 1);
  assert.equal(await page.locator('.chapter-document .rich-content').innerText(), 'İkinci bölümün metni.');
  await page.locator('.cp-ch-btn').first().click();
  assert.equal(await editor.innerText(), 'Bölüm değiştirirken korunan taslak.');
  await page.waitForFunction(() => document.querySelector('.cp-save-details summary')?.textContent === 'Kaydedildi');
  assert(chapter.content.includes('Bölüm değiştirirken'));
  assert.equal(await page.locator('.acb-tour-help-btn').count(), 1);
  await page.getByRole('button', { name: 'Odak', exact: true }).click();
  await page.locator('.focus-veil').waitFor(); await page.locator('.acb-tour-help-btn').waitFor({ state: 'detached' });
  await page.locator('.focus-rich .rich-content').fill('Odak modunda yazılan metin.');
  await page.waitForFunction(() => document.querySelector('.focus-save')?.textContent === 'Kaydedildi');
  await page.keyboard.press('Escape'); await page.locator('.acb-tour-help-btn').waitFor();
  await page.keyboard.press('F11'); await page.locator('.focus-veil').waitFor(); await page.keyboard.press('F11');
  if (CHAPTER_HISTORY_ENABLED) {
  await page.locator('.chapter-document .rich-content').first().fill('Checkpoint öncesi kaydedilmemiş metin.');
  await page.getByRole('button', { name: 'Geçmiş', exact: false }).click();
  await page.getByRole('button', { name: '☆ Bu anı sakla', exact: true }).click();
  await page.getByPlaceholder('Edit öncesi').fill('Edit öncesi');
  await page.getByRole('button', { name: 'Sakla', exact: true }).click();
  await page.getByText("Bu an Geçmiş'te saklandı.", { exact: false }).waitFor();
  assert(versions.some(v => v.isCheckpoint && v.label === 'Edit öncesi'));
  assert(chapter.content.includes('Checkpoint öncesi'));
  const checkpointCount = versions.length;
  await page.getByRole("button", { name: "☆ Bu anı sakla", exact: true }).click();
  await page.getByPlaceholder("Edit öncesi").fill("Edit öncesi");
  await page.getByRole("button", { name: "Sakla", exact: true }).click();
  await page.getByPlaceholder("Edit öncesi").waitFor({ state: "detached" });
  assert.equal(versions.length, checkpointCount);
  await page.screenshot({ path: join(artifacts, "versions.png") });
  await page.locator('.chapter-history-list button').last().click();
  assert.equal(await page.locator(".chapter-history-box .chapter-comparison").count(), 0);
  assert.equal(await page.locator(".chapter-preview [contenteditable]").count(), 0);
  const selectable = await page.locator(".chapter-preview").evaluate(el => { const range=document.createRange(); range.selectNodeContents(el); getSelection().removeAllRanges(); getSelection().addRange(range); return getSelection().toString(); });
  assert(selectable.includes("Paragraf0"));
  await page.getByRole("button", { name: "Karşılaştır", exact: true }).click();
  const compareEditor = page.locator(".chapter-comparison .rich-content");
  await compareEditor.fill("Karşılaştırmada yazılan son taslak.");
  await page.setViewportSize({ width: 390, height: 844 });
  const columns = await page.locator(".chapter-comparison > section").evaluateAll(nodes => nodes.map(n => ({ x:n.getBoundingClientRect().x, y:n.getBoundingClientRect().y })));
  assert.equal(columns[0].x, columns[1].x); assert(columns[1].y > columns[0].y);
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.screenshot({ path: join(artifacts, "comparison.png") });
  await page.getByRole("button", { name: "Karşılaştırmayı kapat" }).click();
  assert.equal(await page.locator(".chapter-history-box .chapter-comparison").count(), 0);
  const previousRevision = chapter.revision;
  const countedBeforeRestore = developmentWords;
  await page.getByRole("button", { name: "Bu metinden devam et" }).click();
  await page.locator('.chapter-history-veil').waitFor({ state: 'detached' }); assert(chapter.content.includes('Paragraf0'));
  assert(versions.some(v => v.content.includes("Karşılaştırmada yazılan son taslak.")));
  assert(chapter.revision > previousRevision);
  assert.equal(developmentWords, countedBeforeRestore);
  await page.getByText("Seçtiğin metinden devam ediyorsun. Önceki taslağın Geçmiş\'te saklandı.", { exact: true }).waitFor();
  }
  developmentWords = 0;
  developmentWords = 3000;
  await page.reload(); await page.locator(".chapter-document").first().waitFor();
  assert.equal(await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).count(), 0);
  assert.equal(developmentRequests, 0);
  developmentWords = 0;
  // Exercise the same preference component mounted in Settings, then refresh.
  preferenceReadFails = true;
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/__writing-test?preferences=1`);
  await page.getByText("Koç tercihin yüklenemedi.", { exact: false }).waitFor();
  assert(await page.getByRole("button", { name: "Gelişim Koçunu Aç", exact: true }).isVisible());
  preferenceReadFails = false;
  await page.getByRole("button", { name: "Gelişim Koçunu Aç", exact: true }).click();
  await page.getByText("Gelişim Koçu açık.", { exact: true }).waitFor();
  assert.equal(coachPreference, "enabled");
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/__writing-test`);
  await page.locator(".chapter-document").first().waitFor();
  assert.equal(await page.locator('.development-archive').count(), 0);
  assert.equal(await page.locator('.development-preference').count(), 0);
  await editor.fill("");
  await page.keyboard.insertText("kelime ".repeat(2999));
  await page.waitForFunction(() => document.querySelector(".cp-save-details summary")?.textContent === "Kaydedildi");
  assert.equal(developmentWords, 2999);
  assert.equal(await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).count(), 0);
  await page.keyboard.type("son");
  await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).waitFor();
  assert.equal(developmentWords, 3000);
  assert.equal(developmentRequests, 0);
  await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).click();
  await page.getByText("Gelişim Koçu henüz kullanıma açılmadı.", { exact: true }).waitFor();
  assert.equal(developmentRequests, 1);
  await page.keyboard.press("Escape");
  developmentCooldown = true;
  await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).click();
  await page.getByText("Yeni yazıların bir sonraki değerlendirme için birikmeye devam edecek.", { exact: true }).waitFor();
  await page.keyboard.press("Escape");
  await editor.evaluate(el => { el.innerHTML = "<p>" + "içe aktarılan ".repeat(10000) + "</p>"; el.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertFromPaste" })); });
  await page.waitForFunction(() => document.querySelector(".cp-save-details summary")?.textContent === "Kaydedildi");
  assert.equal(developmentWords, 20000);
  const beforeDrop = developmentWords;
  await editor.evaluate(el => { el.innerHTML += "<p>Yeni drop metni</p>"; el.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertFromDrop" })); });
  await page.waitForFunction(() => document.querySelector(".cp-save-details summary")?.textContent === "Kaydedildi");
  assert.equal(developmentWords, beforeDrop + 3);
  await editor.evaluate(el => {
    el.dispatchEvent(new CompositionEvent("compositionstart", { bubbles: true }));
    el.innerHTML += "<p>IME metni</p>";
    el.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertCompositionText", isComposing: true }));
    el.dispatchEvent(new CompositionEvent("compositionend", { bubbles: true }));
    el.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertCompositionText" }));
  });
  await page.waitForFunction(() => document.querySelector(".cp-save-details summary")?.textContent === "Kaydedildi");
  assert.equal(developmentWords, beforeDrop + 5);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(350);
  assert(await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).isVisible());
  assert(await page.getByRole("button", { name: "Odak", exact: true }).isVisible());
  assert(await page.locator(".cp-theme-btn").isVisible());
  await page.screenshot({ path: join(artifacts, "development-mobile.png") });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  developmentComplete = true; developmentCooldown = false;
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.waitForFunction(() => !document.querySelector('.cp-development-btn')?.disabled);
  await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).click();
  await page.getByRole("heading", { name: "Test headline" }).waitFor();
  await page.screenshot({ path: join(artifacts, "development-result-mobile.png") });
  await page.getByRole("button", { name: "Kapat", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).count(), 0);
  const requestsAfterSuccess = developmentRequests;
  await page.locator('.cp-tools-menu summary').click();
  await page.getByRole("button", { name: "Son gelişim değerlendirmesi" }).click();
  await page.getByRole("heading", { name: "Test headline" }).waitFor();
  assert.equal(developmentRequests, requestsAfterSuccess);
  await page.getByRole("button", { name: "Kapat", exact: true }).click();
  await page.locator('.cp-tools-menu summary').click();
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.locator('.development-archive-list button').first().click();
  await page.getByRole("heading", { name: "Test headline" }).waitFor();
  await page.getByRole("button", { name: "Kapat", exact: true }).click();
  await page.screenshot({ path: join(artifacts, "development-archive.png") });
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.getByRole("button", { name: "✍️ Atölye", exact: true }).click();
  await page.locator('.atelier-title-input').fill('Egzersiz başlığı');
  await page.locator('.atelier-textarea').fill('Egzersiz metnim korunmalı.');
  await page.getByRole('button', { name: '📖 Bölümler', exact: true }).click();
  await page.getByRole('button', { name: '✍️ Atölye', exact: true }).click();
  assert.equal(await page.locator('.atelier-textarea').inputValue(), 'Egzersiz metnim korunmalı.');
  await page.getByRole('button', { name: 'Nota Kaydet', exact: true }).click();
  await page.getByText('Eserine bağlı nota kaydedildi', { exact: true }).waitFor(); assert.equal(note.workId, 'work1');
  await page.locator('.atelier-textarea').fill('Güncellenmiş egzersiz.');
  await page.getByRole('button', { name: 'Nota Kaydet', exact: true }).click();
  await page.getByText('Eserine bağlı nota kaydedildi', { exact: true }).waitFor(); assert.equal(note.content, 'Güncellenmiş egzersiz.');
  await page.reload(); await page.locator('.chapter-document').first().waitFor();
  await page.getByRole('button', { name: '✍️ Atölye', exact: true }).click();
  assert.equal(await page.locator('.atelier-textarea').inputValue(), 'Güncellenmiş egzersiz.');
  await page.getByRole('button', { name: 'Yardım ve tanıtım turları', exact: true }).click();
  await page.getByRole('button', { name: 'Atölye rehberi', exact: true }).click();
  for (let i = 0; i < 5; i++) { const next = page.getByRole('button', { name: 'İleri', exact: true }); await next.click(); }
  await page.getByText('Yerel yazım ipuçlarını bir araya getirir', { exact: false }).waitFor();
  await page.screenshot({ path: join(artifacts, 'atelier-tour.png') });
  await page.getByRole('button', { name: 'Turu bitir', exact: true }).click();
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/__writing-test?preferences=1`);
  await page.getByRole("button", { name: "Gelişim Koçunu Kapat", exact: true }).click();
  await page.getByText("Gelişim Koçu kapalı.", { exact: true }).waitFor();
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/__writing-test`);
  await page.locator('.chapter-document').first().waitFor();
  assert.equal(await page.locator('.development-archive').count(), 0);
  assert.equal(await page.locator('.development-preference').count(), 0);
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/__writing-test?preferences=1`);
  await page.getByRole("button", { name: "Gelişim Koçunu Aç", exact: true }).click();
  await page.getByText("Gelişim Koçu açık.", { exact: true }).waitFor();
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/__writing-test`);
  await page.locator('.development-archive-list button').first().click();
  await page.getByRole("heading", { name: "Test headline" }).waitFor();
  assert.equal(developmentRequests, requestsAfterSuccess);
  assert.deepEqual(errors, []);
  await page.getByRole("button", { name: "Kapat", exact: true }).click();
  developmentWords = 3000;
  await page.reload();
  await page.getByText('Kalan analiz: 1/2 (24 saat)', { exact: true }).waitFor();
  await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).click();
  await page.getByRole("heading", { name: "Test headline" }).waitFor();
  await page.getByRole("button", { name: "Kapat", exact: true }).click();
  developmentWords = 3000;
  await page.reload();
  await page.getByText('Kalan analiz: 0/2 (24 saat)', { exact: true }).waitFor();
  assert(await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).isDisabled());
  dailySuccesses = 1;
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.getByText('Kalan analiz: 1/2 (24 saat)', { exact: true }).waitFor();
  assert(await page.getByRole("button", { name: "✦ Gelişimimi takip et" }).isEnabled());
  assert.equal(developmentRequests, requestsAfterSuccess + 1);
  console.log('PASS theme/mobile/focus/autosave/history disabled/3000 eligibility/paste/drop/IME/consent/settings/archive retained after opt-out/no real AI/atelier/notes/tour');
  console.log('Screenshots:', artifacts);
} finally { await browser?.close(); await vite.close(); }
